import streamlit as st
import google.generativeai as genai
from PIL import Image
import urllib.parse
from fpdf import FPDF
import requests
from io import BytesIO
import json
import os

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(page_title="ReportSay - AI Lab Interpreter", layout="wide")

# --- 2. SECURE API SETUP ---
# Uses the "Secret" vault we set up in Streamlit
if "MY_API_KEY" in st.secrets:
    genai.configure(api_key=st.secrets["MY_API_KEY"])
else:
    st.error("Missing API Key! Please add 'MY_API_KEY' to Streamlit Secrets.")

# --- 3. UI STYLING ---
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #007bff; color: white; }
    .stExpander { background-color: white; border-radius: 10px; }
    </style>
    """, unsafe_allow_html=True)

# --- 4. NAVIGATION TABS ---
tab1, tab2 = st.tabs(["🔍 AI Report Analysis", "💰 Lab Price Comparison"])

# --- TAB 1: AI REPORT ANALYSIS ---
with tab1:
    st.title("📊 ReportSay")
    st.subheader("Your AI-Powered Medical Lab Assistant")
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        uploaded_file = st.file_uploader("Upload Lab Report (Image/PDF)", type=['png', 'jpg', 'jpeg', 'pdf'])
        language = st.radio("Interpretation Language", ["English", "Urdu (اردو)"])
        
    with col2:
        st.info("💡 **How it works:** Upload your report, and our AI will explain the values in simple terms based on your preferred language.")

    if uploaded_file:
        # Display the uploaded image
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Report", use_container_width=True)
        
        if st.button("Analyze Report"):
            with st.spinner("Analyzing your report... Please wait."):
                # AI Prompt Logic
                prompt = f"Interpret this medical lab report in {language}. Explain high/low values and suggest next steps. Use simple terms."
                model = genai.GenerativeModel('gemini-1.5-flash')
                response = model.generate_content([prompt, image])
                
                st.success("Analysis Complete!")
                st.markdown("### 📝 Interpretation")
                st.write(response.text)
                
                # PDF Download Feature
                pdf = FPDF()
                pdf.add_page()
                pdf.set_font("Arial", size=12)
                pdf.cell(200, 10, txt="ReportSay - AI Analysis", ln=1, align='C')
                pdf.multi_cell(0, 10, txt=response.text)
                pdf_output = pdf.output(dest='S').encode('latin-1', 'replace')
                st.download_button(label="Download Analysis as PDF", data=pdf_output, file_name="ReportSay_Analysis.pdf", mime="application/pdf")

# --- TAB 2: DYNAMIC PRICE CHECKER ---
with tab2:
    st.title("💰 Smart Price Checker")
    st.markdown("Compare live prices across **Mughal, SKM, Al-Noor, IDC, and Chughtai**.")
    
    # Path to the data generated by your scraper robot
    json_path = 'data/lab_prices.json'
    
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r') as f:
                lab_database = json.load(f)
            
            # Get the update time from the file
            last_updated = os.path.getmtime(json_path)
            import datetime
            st.caption(f"🕒 Last updated: {datetime.datetime.fromtimestamp(last_updated).strftime('%Y-%m-%d %H:%M')}")

            search_query = st.text_input("Enter Lab Test Name (e.g. CBC, Vitamin D, Glucose):").strip().upper()
            
            if search_query:
                results_found = False
                cols = st.columns(3)
                col_idx = 0
                
                for lab_name, tests in lab_database.items():
                    with cols[col_idx % 3]:
                        st.markdown(f"### 🏥 {lab_name}")
                        lab_matches = {k: v for k, v in tests.items() if search_query in k.upper()}
                        
                        if lab_matches:
                            for test, price in lab_matches.items():
                                st.success(f"**{test}**\n\nPrice: **Rs. {price}**")
                            results_found = True
                        else:
                            st.warning(f"No match at {lab_name}")
                    col_idx += 1
                
                if not results_found:
                    st.error(f"No labs found offering '{search_query}' in our database.")
            else:
                st.write("Enter a test name above to compare prices.")
                
        except Exception as e:
            st.error(f"Error reading database: {e}")
    else:
        st.warning("🔄 Our robot is currently fetching the latest prices. Please refresh in 2 minutes.")
        st.info("The price-checker will be active as soon as the 'Daily Lab Price Update' workflow completes.")

# --- 5. FOOTER ---
st.markdown("---")
st.caption("Disclaimer: ReportSay is an AI assistant and should not replace professional medical advice. Always consult with a doctor.")
